// Generated by gencpp from file custom_msgs/Detections.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_DETECTIONS_H
#define CUSTOM_MSGS_MESSAGE_DETECTIONS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <custom_msgs/Detection.h>

namespace custom_msgs
{
template <class ContainerAllocator>
struct Detections_
{
  typedef Detections_<ContainerAllocator> Type;

  Detections_()
    : header()
    , detections()  {
    }
  Detections_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , detections(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::custom_msgs::Detection_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::custom_msgs::Detection_<ContainerAllocator> >> _detections_type;
  _detections_type detections;





  typedef boost::shared_ptr< ::custom_msgs::Detections_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::Detections_<ContainerAllocator> const> ConstPtr;

}; // struct Detections_

typedef ::custom_msgs::Detections_<std::allocator<void> > Detections;

typedef boost::shared_ptr< ::custom_msgs::Detections > DetectionsPtr;
typedef boost::shared_ptr< ::custom_msgs::Detections const> DetectionsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::Detections_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::Detections_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_msgs::Detections_<ContainerAllocator1> & lhs, const ::custom_msgs::Detections_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.detections == rhs.detections;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_msgs::Detections_<ContainerAllocator1> & lhs, const ::custom_msgs::Detections_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::Detections_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::Detections_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::Detections_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::Detections_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::Detections_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::Detections_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::Detections_<ContainerAllocator> >
{
  static const char* value()
  {
    return "81f9cb6999cd28efac836bbb8d43899e";
  }

  static const char* value(const ::custom_msgs::Detections_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x81f9cb6999cd28efULL;
  static const uint64_t static_value2 = 0xac836bbb8d43899eULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::Detections_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/Detections";
  }

  static const char* value(const ::custom_msgs::Detections_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::Detections_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"Detection[] detections\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: custom_msgs/Detection\n"
"# An individual detection\n"
"string class_name           # e.g. \"soccer_ball\", \"traffic_cone\", \"stop_sign\", \"person\", \"chair\"\n"
"float32 confidence          # detection confidence [0.0 to 1.0]\n"
"int32 x_min                 # bounding box pixel coords\n"
"int32 y_min\n"
"int32 x_max\n"
"int32 y_max\n"
"string detected_color       # e.g. \"red\", \"green\", \"blue\", \"yellow\", \"orange\"\n"
"string shape                # e.g. \"spherical\", \"conical\", \"octagonal\", \"human\", \"chair-like\"\n"
;
  }

  static const char* value(const ::custom_msgs::Detections_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::Detections_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.detections);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Detections_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::Detections_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::Detections_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "detections[]" << std::endl;
    for (size_t i = 0; i < v.detections.size(); ++i)
    {
      s << indent << "  detections[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::custom_msgs::Detection_<ContainerAllocator> >::stream(s, indent + "    ", v.detections[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_DETECTIONS_H
